### ISSUE TITLE
Jump scare in one of the links on VideoPiracyGuide.md

### ISSUE THREAD

**Issue by abdlhay** [fmhy/FMHYedit#1037]
femboy.live has a jump scare took my 4th soul away hope you remove it

**Comment by erikk333** [comment]
![image](https://github.com/fmhy/FMHYedit/assets/147526653/018d989a-5981-4ce8-bb9d-cb77ba4f8710)
 its empty and not in fmhy either

**Comment by nbats** [comment]
I don't see it in the wiki

**Comment by abdlhay** [comment]
my bad, domain i provided misses 's' its femboys.live
![20231027_235623](https://github.com/fmhy/FMHYedit/assets/44603158/581796a3-7216-4f17-963a-395c23bd3796)

**Comment by nbats** [comment]
yeah we removed it a long time ago
