### ISSUE TITLE
New NSFW torrent site

### ISSUE THREAD

**Issue by Dispatch3376** [fmhy/FMHYedit#1040]
https://xxxclub.to/

**Comment by Dispatch3376** [comment]
TGx mirror profile https://torrentgalaxy.to/profile/NoisyBoY

**Comment by nbats** [comment]
Added thank you

**Comment by Dispatch3376** [comment]
Please star xxxclub it has a nice UI and is the most active one so far

**Comment by nbats** [comment]
gotcha will do
