### ISSUE TITLE
Change "Tweaking" section in System Tools

### ISSUE THREAD

**Issue by Kr-cK** [fmhy/FMHYedit#1120]
I thought "github.com/amitxv/PC-Tuning" could be starred in the Tweaking section. It's updated far more frequently than other tweaking resources. Also more transparent than any other debloating solutions and whatnot. Pretty useful. Also, the "Redwan’s Guide to guides" in the same section seems to be unmaintained and contains lots of dead links. Do what you want with that. :smiley:

**Comment by nbats** [comment]
Hey thanks for the heads up, I got PC-Tuning starred and Redwan removed.
