### ISSUE TITLE
Movie/TV/Anime Site: movieworld.pl

### ISSUE THREAD

**Issue by mpaunovic** [fmhy/FMHYedit#1151]
Hi guys,

Could you please add **movieworld.pl** to the stream videos section? It's a great new site and it's clean:

https://www.urlvoid.com/scan/movieworld.pl/

https://www.virustotal.com/gui/url/13fae3b64991ce267e8ac43ff09932475e6aec893998511dd38cb509c9ed4aa4

Thank you and keep it up! :)

**Comment by nbats** [comment]
yeah we'll check it out, thank you.
