### ISSUE TITLE
Uloz.to - ends 1.12.

### ISSUE THREAD

**Issue by Vojtak42** [fmhy/FMHYedit#1164]
On 1 December 2023, significant changes will be made to the operation of the Ulož.to Disk and PINKfile.cz cloud storage services. The changes are a forced response to the incoming European legislation known as the DSA.
From Friday 1 December 2023, cloud storage services will only be available to registered users. They will be able to handle only the files they uploaded to the storage. Files cannot be shared publicly, even by link. Of course, users don't have to worry about losing any of their personal files. Everything on the cloud storage remains, but the content will only be accessible to users who have uploaded it to the storage themselves.

**Comment by nbats** [comment]
Got it removed, thanks for the heads up
