### ISSUE TITLE
sms-verification-sites link leads to another page

### ISSUE THREAD

**Issue by masterofobzene** [fmhy/FMHYedit#1205]
The link "SMS Verification Sites" that is nested here: https://fmhy.net/adblockvpnguide#privacy-tools

Leads to a wrong link -> https://fmhy.net/storage#sms-verification-sites  that doesn't have the requested information.

**Comment by BismutoGanymedes** [comment]
Have you actually tried it?

Clicking on the "sms verification sites" shows this page:
![2023-12-04 19-25-06](https://github.com/fmhy/FMHYedit/assets/121880486/2775868b-4f06-4250-888c-ca80a5aa15c6)

**Comment by nbats** [comment]
Yeah I'm sorry I'm not sure but when I click it goes to SMS verification. Maybe its some sort of extension or the browser you're on.
