### ISSUE TITLE
remove inactive channels from Android / iOS > TG Channels section

### ISSUE THREAD

**Issue by XCE0** [fmhy/FMHYedit#1235]
[Referenced section](https://fmhy.pages.dev/android-iosguide#tg-channels)

The following telegram channels are no longer distributing modded android apps:

- https://t.me/s/DroidApks
- https://t.me/s/Glype
- https://t.me/s/faloojein
- https://t.me/s/IC_Mods
- https://t.me/s/Moderse

**Comment by nbats** [comment]
thanks for the update, got em all removed.
