### ISSUE TITLE
Replace/Remove JustEmuTarkov

### ISSUE THREAD

**Issue by Likroll** [fmhy/FMHYedit#1237]
https://fmhy.pages.dev/gamingpiracyguide#single-games

From what I've tested, the website is gone.
An alternative might be [SPT-AKI](https://www.sp-tarkov.com/), which might be a better fit in the game mods section.

**Comment by nbats** [comment]
alright thanks, I don't see JustEmuTarkov in the wiki, but we will check out the other.
