### ISSUE TITLE
Add Supatabs to [ Storage > Tab Managers ]

### ISSUE THREAD

**Issue by XCE0** [fmhy/FMHYedit#1240]
[Referenced Section ](https://fmhy.pages.dev/storage#tab-managers)

[Supatabs addon link](https://chromewebstore.google.com/detail/icbcnjlaegndjabnjbaeihnnmidbfigk)

[Relevant reddit post
](https://old.reddit.com/r/chrome/comments/xoa4dr/i_built_a_fresh_feature_rich_alternative_chrome/)

**Comment by nbats** [comment]
got it added thank you
