### ISSUE TITLE
Broken links of IPTV Tools in Storage

### ISSUE THREAD

**Issue by GLSW2020** [fmhy/FMHYedit#1242]
In [IPTV Tools](https://fmhy.net/storage#iptv-tools), the links under [SmartTV Players](https://fmhy.net/storage#android-tv-iptv-players) and [HLS Downloaders](https://fmhy.net/storage#hls-downloaders) just redirect to the storage page.

**Comment by nbats** [comment]
fixed thanks for the heads up
