### ISSUE TITLE
Add Freelancing/Earning Sites

### ISSUE THREAD

**Issue by callmereaper** [fmhy/FMHYedit#1269]
Sorry If I Am Doing Anything Wrong But I Didn’t See Any Freelancing Sites On FMHY. Or Am I Blind? Can You Add Some?

**Comment by qiracy** [comment]
Hey there, yeah we don't have much stuff related to freelance, although you could check out some sites in the Remote Jobs category as they sometimes list freelance jobs as well. Other than that, you're welcome to suggest new sites to add.

**Comment by callmereaper** [comment]
I Am Unaware Of Freelance Sites And That is Why I’m Asking!

Anyway I Have Some Movie Sites Here 

10BitClub : https://10bitclub.me/
Description : 10bitClub is a team of 10 encoders that encode movies in the best possible way. Through this website we only intend to bring you the best quality files at one place. Only files from members of the 10bitClub team will be posted here.
Their Telegram : https://t.me/tenbitclub


IDK The Title Of This But This One Has Mostly Small 60FPS Movies And Series, Kindly Check Out!

https://www.areaindex.my.id/
Their Telegram Channel : https://t.me/AIOReleases

**Comment by nbats** [comment]
thank you, we'll get them added to our link queue and check them out when we can.
