### ISSUE TITLE
Remove eporner

### ISSUE THREAD

**Issue by Turhvjbufv** [fmhy/FMHYedit#1278]
It is full of ads,  and clicking on the video also opens up an ad,  and navigating in video also opens ads

**Comment by qiracy** [comment]
I'd recommend using an adblocker, especially considering almost every site is filled with ads nowadays. UBlockOrigin is a good choice: https://github.com/gorhill/uBlock#installation

**Comment by Turhvjbufv** [comment]
Using brave inbuilt blocker

**Comment by nbats** [comment]
yeah sorry but we have to keep others in mind and it works totally fine with ublock.
