### ISSUE TITLE
Monthly updates RSS Feed / Atom and Progressive Web App (PWA)

### ISSUE THREAD

**Issue by Fun-Ken** [fmhy/FMHYedit#1280]
Hello,

I propose to introduce an RSS feed / Atom for monthly FMHY updates. 

In addition, I think it may be useful to create a PWA (progressive web app) for FMHY (https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps).

**Comment by nbats** [comment]
Thanks for the suggestion, I don't know much about this myself but I'll pass it along and see what others think.

**Comment by taskylizard** [comment]
> In addition, I think it may be useful to create a PWA (progressive web app) for FMHY ([developer.mozilla.org/en-US/docs/Web/Progressive_web_apps](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps)).

A PWA was initially added but later removed because we make changes almost every hour and want to serve latest revisions, could look into it again.

**Comment by taskylizard** [comment]
We now have a rss feed: https://fmhy.net/feed.rss

Hope you enjoy FMHY!
