### ISSUE TITLE
License

### ISSUE THREAD

**Issue by couleurm** [fmhy/FMHYedit#1290]
Under what license is FMHY's markdown source text files?

The answer as of writing this is that there's no license files, which defaults to: https://choosealicense.com/no-permission/

Though would you be open to people embedding FMHY on their website or you do not want people messing with your stuff?

**Comment by nbats** [comment]
Yeah its 100% open, people can do whatever they'd like with it. Multiple people have already taken the markdown and made their own versions of FMHY, or even websites like elon did with fmhy.tk or tasky did with fmhy.net.

**Comment by kir0ul** [comment]
How about adding a `LICENSE` file to the repo then? Something like:
- https://choosealicense.com/licenses/wtfpl/
- https://choosealicense.com/licenses/unlicense/
- https://creativecommons.org/publicdomain/zero/1.0/

**Comment by InternetNinjo** [comment]
and why is that?

**Comment by kir0ul** [comment]
Just to make it clear, otherwise people are wondering, like in https://github.com/fmhy/edit/issues/1290#issue-2060349620.

**Comment by beedell-roke** [comment]
@nbats, without an explicitly copyleft `LICENSE`, this repository is *not* freely usable, because many jurisdictions (including where GitHub is based) assign implicit rights that must be explicitly withdrawn by the copyright owner.
