### ISSUE TITLE
OlaMovies

### ISSUE THREAD

**Issue by IronManMarkRDJ** [fmhy/FMHYedit#1292]
Change the URL of OlaMovies in [Beginners Guide](https://fmhy.net/beginners-guide#downloading), [Movies / TV / Anime](https://fmhy.net/videopiracyguide#download-sites) and [Non-English](https://fmhy.net/non-english#downloading-6) to [this new URL](http://olamovies.yachts/).

**Comment by nbats** [comment]
will do thank you
