### ISSUE TITLE
Remove Modyolo from Modded APKs sections

### ISSUE THREAD

**Issue by XCE0** [fmhy/FMHYedit#1303]
[Referenced Section](https://fmhy.pages.dev/android-iosguide#modded-apks)

There has been a lot of reports of malware on Modyolo.

[Relevant Reddit link.](https://old.reddit.com/search?q=modyolo)

**Comment by nbats** [comment]
Sorry but we need actual proof via virustotal, people claim sites are unsafe all the time when its just false positives.
