### ISSUE TITLE
Cs.rin.ru does not appear in searches.

### ISSUE THREAD

**Issue by DogancanYr** [fmhy/FMHYedit#1359]
It's on Megathread, but it doesn't appear in the search field.

**Comment by nbats** [comment]
seems to be showing up for me: 

https://imgur.com/a/VDFvkNW

**Comment by DogancanYr** [comment]
> seems to be showing up for me:
> 
> https://imgur.com/a/VDFvkNW

Cs.rinmega appears to be not the main site.

**Comment by nbats** [comment]
yeah you're right its only showing their megathread but their site link isn't showing up. Not sure if there's anything we can do but I'll let tasky know.
