### ISSUE TITLE
Adding section for Creative Commons licensed content.

### ISSUE THREAD

**Issue by XCE0** [fmhy/FMHYedit#1386]
I think it's pretty worthy to add a section for freely licensed content, so for example under that section we can add news subsection (propublica,Theconversation,...etc).

In my opinion, adding this section to the website will make FMHY more comprehensive as a online resource.

**Comment by nbats** [comment]
Sure I dont see why not. I'm not sure if we have enough stuff for a section, but if you can organize a list of good sites here or in a pastebin we could maybe make a section out of it.

**Comment by XCE0** [comment]
News:
[ProPublica](https://www.propublica.org/) - https://www.propublica.org/steal-our-stories/
[The Conversation](https://theconversation.com/) - https://theconversation.com/global/republishing-guidelines
[openDemocracy](https://www.opendemocracy.net/en/) - https://www.opendemocracy.net/en/write-for-us/
[Knowable Magazine](https://knowablemagazine.org/) - https://knowablemagazine.org/republish
[Kaiser Health News](https://khn.org/) - https://kffhealthnews.org/syndication/
[Reveal](https://revealnews.org/) - https://revealnews.org/republishing-guidelines/
[Wikinews](https://en.wikinews.org/wiki/Main_Page)
[TorrentFreak](https://torrentfreak.com/) - https://torrentfreak.com/copyright/
[The Markup](https://themarkup.org/) - https://themarkup.org/about
[Science in the News](https://sitn.hms.harvard.edu/)
[Common Dreams](https://www.commondreams.org/news) - https://www.commondreams.org/republishing-our-work
[E-International Relations](https://www.e-ir.info/) - https://www.e-ir.info/reference/
[The Bureau of Investigative Journalism](https://www.thebureauinvestigates.com/stories) - https://www.thebureauinvestigates.com/about-us/use-our-work
[wikipedia News](https://en.wikipedia.org/wiki/Portal:Current_events), [Wiki News](https://en.wikinews.org/wiki/Main_Page)

Articles:
[The New Humanitarian](https://www.thenewhumanitarian.org/) - https://www.thenewhumanitarian.org/Republish
[The New Inquiry](https://thenewinquiry.com/) - https://thenewinquiry.com/terms-of-use/
[Pesquisa FAPESP](https://revistapesquisa.fapesp.br/en/) - https://revistapesquisa.fapesp.br/en/republication-policy/
[In The Fray](https://inthefray.org/) - https://inthefray.org/republishing/ ( the last article is From JUNE 2, 2023) 
[Tricontinental: Institute for Social Research](https://thetricontinental.org/) - https://thetricontinental.org/privacy-and-creative-commons/
[OpenMind](https://www.openmindmag.org/) - https://www.openmindmag.org/republish-our-content-for-free
[Open Society Foundations](https://www.opensocietyfoundations.org/publications) - https://www.opensocietyfoundations.org/policies/terms-and-conditions
[Mosaic](https://mosaicscience.com/)
[YES! Media](https://www.yesmagazine.org/) - https://www.yesmagazine.org/about-reprints
[Pluralistic](https://pluralistic.net/)
[Gwern Branwen](https://www.gwern.net/index) - https://gwern.net/about#license
[Global Investigative Journalism Network](https://gijn.org/) - https://gijn.org/about-us/use-our-stuff-gijns-republishing-guidelines/
[Global Voices](https://globalvoices.org/) - https://globalvoices.org/about/global-voices-attribution-policy/
[Electronic Frontier Foundation](https://www.eff.org/updates) - https://www.eff.org/copyright
[Human Rights Watch](https://text.hrw.org/) - https://text.hrw.org/permissions#2

Learning Recources:
[Saylor Academy](https://learn.saylor.org/) - https://www.saylor.org/open/licensing-information/

Pictures: ( notice that due to the giant amount of websites offering free photos, my criteria here wast to choose websites that works without javascript and being high quality.)
[WikiMedia](https://commons.wikimedia.org/wiki/Main_Page)
[Picography](https://picography.co/) - https://picography.co/terms/
[ISO Republic ](https://isorepublic.com/) - https://isorepublic.com/license/
[StockSnap](https://stocksnap.io/) - https://stocksnap.io/license
[NegativeSpace](https://negativespace.co/) - https://negativespace.co/license/
[ShotStash](https://shotstash.com/) - https://shotstash.com/license/

Comics:
[XKCD](https://xkcd.com/) - https://xkcd.com/license.html

I think it's worth opening the issue for the team to draft the list and to discuss it.

**Comment by XCE0** [comment]
Comics:

https://poorlydrawnlines.com/

**Comment by taskylizard** [comment]
You should join our [Discord](https://discord.gg/Stz6y6NgNg) to discuss about this! I would love a CCs media section.

**Comment by XCE0** [comment]
I don't have discord.

**Comment by taskylizard** [comment]
You can probably use divolt then, communications in real time help speed up tasks like this.

**Comment by nbats** [comment]
Closing this for now, but we did add this page to our list of things to-do, so you're welcome to keep updating your list here and we'll a new section made when we can.
