### ISSUE TITLE
Site Removal thebypasser.com

### ISSUE THREAD

**Issue by SledMasterFred** [fmhy/FMHYedit#1550]
Remove **https://thebypasser.com/** Be Removed From **https://fmhy.net/adblockvpnguide#redirect-bypass** as it is full of ads, redirects, and better alternatives have been provided

This Below is an Image of the site with AdNauseam and MalwareBytes Browser Guard enabled. Lots of ads.
![image](https://github.com/fmhy/FMHYedit/assets/126551205/0cbbe168-2954-4eff-8eb6-89f91e6bba34)

**Comment by DogancanYr** [comment]
> Remove **https://thebypasser.com/** Be Removed From **https://fmhy.net/adblockvpnguide#redirect-bypass** as it is full of ads, redirects, and better alternatives have been provided
> 
> This Below is an Image of the site with AdNauseam and MalwareBytes Browser Guard enabled. Lots of ads. ![image](https://private-user-images.githubusercontent.com/126551205/304847106-0cbbe168-2954-4eff-8eb6-89f91e6bba34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NDAxMzEsIm5iZiI6MTcwNzkzOTgzMSwicGF0aCI6Ii8xMjY1NTEyMDUvMzA0ODQ3MTA2LTBjYmJlMTY4LTI5NTQtNGVmZi04ZWI2LTg5ZjkxZTZiYmEzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQxOTQzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmU1M2E0YTFkMmQyMDcwZTRkZjVlM2JkNTlkMDdjMGE5Zjg5N2E2NTkwNjJiNzA5Njk0MWNjMmRlOTczZmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MN262rLtONjGrxY_udzis1QblzddW3EenaGdKLuZgDg)

Just use ad blocker.

**Comment by SledMasterFred** [comment]
> > Remove **https://thebypasser.com/** Be Removed From **https://fmhy.net/adblockvpnguide#redirect-bypass** as it is full of ads, redirects, and better alternatives have been provided
> > This Below is an Image of the site with AdNauseam and MalwareBytes Browser Guard enabled. Lots of ads. ![image](https://private-user-images.githubusercontent.com/126551205/304847106-0cbbe168-2954-4eff-8eb6-89f91e6bba34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NDAxMzEsIm5iZiI6MTcwNzkzOTgzMSwicGF0aCI6Ii8xMjY1NTEyMDUvMzA0ODQ3MTA2LTBjYmJlMTY4LTI5NTQtNGVmZi04ZWI2LTg5ZjkxZTZiYmEzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQxOTQzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmU1M2E0YTFkMmQyMDcwZTRkZjVlM2JkNTlkMDdjMGE5Zjg5N2E2NTkwNjJiNzA5Njk0MWNjMmRlOTczZmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MN262rLtONjGrxY_udzis1QblzddW3EenaGdKLuZgDg)
> 
> Just use ad blocker.

I just showed you the image with my ad blockers AdNauseam & Malwarebytes on

**Comment by DogancanYr** [comment]
> > > Remove **https://thebypasser.com/** Be Removed From **https://fmhy.net/adblockvpnguide#redirect-bypass** as it is full of ads, redirects, and better alternatives have been provided
> > > This Below is an Image of the site with AdNauseam and MalwareBytes Browser Guard enabled. Lots of ads. ![image](https://private-user-images.githubusercontent.com/126551205/304847106-0cbbe168-2954-4eff-8eb6-89f91e6bba34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NDAxMzEsIm5iZiI6MTcwNzkzOTgzMSwicGF0aCI6Ii8xMjY1NTEyMDUvMzA0ODQ3MTA2LTBjYmJlMTY4LTI5NTQtNGVmZi04ZWI2LTg5ZjkxZTZiYmEzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQxOTQzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmU1M2E0YTFkMmQyMDcwZTRkZjVlM2JkNTlkMDdjMGE5Zjg5N2E2NTkwNjJiNzA5Njk0MWNjMmRlOTczZmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MN262rLtONjGrxY_udzis1QblzddW3EenaGdKLuZgDg)
> > 
> > 
> > Just use ad blocker.
> 
> I just showed you the image with my ad blockers AdNauseam & Malwarebytes on

I didn't even know they ad blocking plugins. Use ublock origin and don't use 2 at the same time

**Comment by SledMasterFred** [comment]
> > > > Remove **https://thebypasser.com/** Be Removed From **https://fmhy.net/adblockvpnguide#redirect-bypass** as it is full of ads, redirects, and better alternatives have been provided
> > > > This Below is an Image of the site with AdNauseam and MalwareBytes Browser Guard enabled. Lots of ads. ![image](https://private-user-images.githubusercontent.com/126551205/304847106-0cbbe168-2954-4eff-8eb6-89f91e6bba34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NDAxMzEsIm5iZiI6MTcwNzkzOTgzMSwicGF0aCI6Ii8xMjY1NTEyMDUvMzA0ODQ3MTA2LTBjYmJlMTY4LTI5NTQtNGVmZi04ZWI2LTg5ZjkxZTZiYmEzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQxOTQzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmU1M2E0YTFkMmQyMDcwZTRkZjVlM2JkNTlkMDdjMGE5Zjg5N2E2NTkwNjJiNzA5Njk0MWNjMmRlOTczZmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MN262rLtONjGrxY_udzis1QblzddW3EenaGdKLuZgDg)
> > > 
> > > 
> > > Just use ad blocker.
> > 
> > 
> > I just showed you the image with my ad blockers AdNauseam & Malwarebytes on
> 
> I didn't even know they ad blocking plugins. Use ublock origin and don't use 2 at the same time

AdNauseam is a fork of uBo, and Malwarebytes is an antivirus software for antiviral things.

**Comment by DogancanYr** [comment]
> > > > > Remove **https://thebypasser.com/** Be Removed From **https://fmhy.net/adblockvpnguide#redirect-bypass** as it is full of ads, redirects, and better alternatives have been provided
> > > > > This Below is an Image of the site with AdNauseam and MalwareBytes Browser Guard enabled. Lots of ads. ![image](https://private-user-images.githubusercontent.com/126551205/304847106-0cbbe168-2954-4eff-8eb6-89f91e6bba34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NDAxMzEsIm5iZiI6MTcwNzkzOTgzMSwicGF0aCI6Ii8xMjY1NTEyMDUvMzA0ODQ3MTA2LTBjYmJlMTY4LTI5NTQtNGVmZi04ZWI2LTg5ZjkxZTZiYmEzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQxOTQzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmU1M2E0YTFkMmQyMDcwZTRkZjVlM2JkNTlkMDdjMGE5Zjg5N2E2NTkwNjJiNzA5Njk0MWNjMmRlOTczZmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MN262rLtONjGrxY_udzis1QblzddW3EenaGdKLuZgDg)
> > > > 
> > > > 
> > > > Just use ad blocker.
> > > 
> > > 
> > > I just showed you the image with my ad blockers AdNauseam & Malwarebytes on
> > 
> > 
> > I didn't even know they ad blocking plugins. Use ublock origin and don't use 2 at the same time
> 
> AdNauseam is a fork of uBo, and Malwarebytes is an antivirus software for antiviral things.

It doesn't work correctly or you need to add a filter list.

**Comment by nbats** [comment]
Yeah I just tried it in Firefox with ubo and updated filters and I get no ads.
