### ISSUE TITLE
Wiki: Presenting Starred Sites

### ISSUE THREAD

**Issue by GLSW2020** [fmhy/FMHYedit#1610]
### Type

Site suggestion

### Add additional context

The site has an option to toggle Starred sites which will then only show the starred sites. Now, the problem with that is, some categories don't have any starred sites so only their heading show up nothing else. I think a good way to alleviate this problem would be to move these very few sub-categories to Storage for a while until a "Star-worthy" site is found.

**Comment by taskylizard** [comment]
This is a known issue.
