### ISSUE TITLE
OlaMovies URL Change

### ISSUE THREAD

**Issue by GLSW2020** [fmhy/FMHYedit#1699]
### Type

Site suggestion

### Add additional context

[OlaMovies New URL](https://olamovies.icu/)
Changes at [Beginners Guide](https://fmhy.xyz/beginners-guide#downloading), [Movies / TV / Anime](https://fmhy.xyz/videopiracyguide#download-sites) and [Non-English](https://fmhy.xyz/non-english#downloading-5).

**Comment by nbats** [comment]
thanks got it updated

**Comment by GLSW2020** [comment]
Should I be suggesting this kind of changes on GitHub or Discord? If Discord, then which channel?

**Comment by nbats** [comment]
Either is totally fine, but if you do want to use discord then the #to-do channel would be best.

**Comment by GLSW2020** [comment]
Thanks!
