### ISSUE TITLE
Brave Search Goggles

### ISSUE THREAD

**Issue by Dispatch3376** [fmhy/FMHYedit#1723]
### Type

Site suggestion

### Add additional context

Brave Goggles is like Google CSE; Brave has its own independent search index, and Google has been known to censor search results and block some websites.
It would be a nice second option to have alongside Google's CSE

https://search.brave.com/goggles/discover
https://github.com/brave/goggles-quickstart

https://search.brave.com/goggles?q=Oppenheimer&source=web&goggles_id=https%3A%2F%2Fgist.githubusercontent.com%2FNiek%2F238fb65384da1d9af302953bbcac6f70%2Fraw  (example)

**Comment by nbats** [comment]
thanks for the suggestion, we'll check it out
