### ISSUE TITLE
Vimm's Lair Takedown

### ISSUE THREAD

**Issue by winterviola** [fmhy/FMHYedit#1909]
### Type

Site suggestion

### Add additional context

Vimm's Lair recently had all of it's nintendo content taken down, so a note about that should probably be added and have it bumped down in the ROM list (or unstarred entirely).

https://twitter.com/PC_Nation__/status/1790673595535868383?t=7PVuBEPHYb51lC39j8OOrw&s=19

**Comment by officialkaizen** [comment]
Hey winterviola thank's for bringing this to our attention. 
It's seems that it's only 717 titles that are offline, and it may even be a fake notice. Majority of Nintendo's games & other ROMs are still available on vimm. 
source: https://vimm.net/bbs/?p=viewPost&Post=33301
For now I think we can keep it starred / unchanged while we wait for this incident to develop further.

**Comment by nullish-cat** [comment]
Just chipping in - even if it is a troll like Vimm says, it's very likely Nintendo will give in either way like with the GMod situation, especially given that these are roms and Nintendo is notorious with these kinds of takedowns. Not to mention that Nintendo is now aware of this site and will probably hunt down the rest of the ROMs on there.

Regardless, if it's just the ~700 titles, I'd say this is still an unstar. 99% of people getting roms want those first-party nintendo titles (Mario, Zelda, etc.) and the majority of them will now be missing. It would still be good for other ROMs, yeah, but there are better sites for these now.

**Comment by nbats** [comment]
Someone correct me if I'm wrong but looks like all nintendo games are back? I just tried both NES and N64 with no issues.

**Comment by nullish-cat** [comment]
![image](https://github.com/fmhy/FMHYedit/assets/141464552/80827f5b-be66-42ab-b0e3-0e47ba4779e3)
Still taken down.

**Comment by nbats** [comment]
okay I see, I'll get it ustarred
