### ISSUE TITLE
Base64 Rentry - dead links

### ISSUE THREAD

**Issue by dev-bd** [fmhy/FMHYedit#1975]
### Type

Bad sites

### Add additional context

Hey, noticed a dead link on the Base64 Rentry and decided to go through the entire document. Note that some of the sites could have simply been down at the time I checked. Others seem to be indefinitely offline. It took a while to check everything, so I hope I can help keep the site fresh (well, the linked FMHY document, which I assume you can still access).

I'll refer to the links by their "section" / title; if there is more than one link in a section I'll specify which one is broken (most have like, 3 max). My list should also be in order from the top down.

**Dead / Broken Sites:**
**80s** - site seems to be unrelated to the original purpose + have a new owner.
**Squid Proxy** - "Site is shut down for now. Thanks for everything :)". not sure how long it's been shut down. "for now" is not reassuring.
**Hacked Super Mario** - dead.
**Rhapsody** - dead?
**TYLER** - dead?
**Arquivista (LINK 1)** - google doc deleted.
**FlixHub** - taken down, I sideload all my movie apps but versions uploaded to the actual app store are usually found sooner or later lol. there seems to be a new one, but I'd just link to an IPA or delete.
**MegaFlix** - same thing as FlixHub. I actually use a sideloaded IPA for this one, but it's not on the app store now.
**server.elscione** - dead?

**Comment by nbats** [comment]
Thanks for letting us know, just got them all removed from both the wiki and base64 page.
