### ISSUE TITLE
Non-English minor spelling fix & JP duplicate

### ISSUE THREAD

**Issue by WNnitro** [fmhy/FMHYedit#2004]
### Type

Grammar / Markdown

### Add additional context

![image](https://github.com/fmhy/FMHYedit/assets/70445335/7880b357-8529-4eb9-89eb-90a8477d32ac)

fixed:
`This section can be used to get movies, music, books, courses, etc. but for anything you install, like games, software, or APKs, it's highly recommended to use the English sections instead. The only exceptions are sites like m0nkrus that have very good reputations. Keep in mind that you can always change the language in the installers.`

---

![image](https://github.com/fmhy/FMHYedit/assets/70445335/787c03a1-5d64-4d5a-820b-0f573eee9fed)

duplicate in "reading", here's some explanation
![image](https://github.com/fmhy/FMHYedit/assets/70445335/5458a747-b133-428b-9c30-15789efc305f)
![image](https://github.com/fmhy/FMHYedit/assets/70445335/ea727384-06cc-4470-8e98-1b8beeafd9b8)

sorry for the minor change.
im frisk btw.

**Comment by nbats** [comment]
thank you got it fixed
