### ISSUE TITLE
 Non-English /Persian sites

### ISSUE THREAD

**Issue by amirnsz** [fmhy/FMHYedit#2073]
### Type

Bad sites

### Add additional context

Persian movie sites that require a paid subscription or are censored:
1.https://dlfars.ir/
2.https://www.f2mx.ir/
3.https://dlrozaneh.ir/
4.https://tikfilmz.ir/
5.http://www.ganjdl.ir/
6.https://karanmovie.org/
7.https://hamrahmoviez.ir/
8.https://hexdl.com/
9.https://pishgammovies.ir/
10.https://centerdl.ir/

**Comment by nbats** [comment]
thanks for reporting, I'll get them removed
