### ISSUE TITLE
Tags for FOSS software/Privacy-respecting software.

### ISSUE THREAD

**Issue by kushagra-xo** [fmhy/FMHYedit#2090]
### Type

Grammar / Markdown

### Add additional context

would it make sense to have tags, like stars, to mention which software is free and open source? this will definitely help the people pick software that aligns with their beleifs, and which respects privacy.

**Comment by nbats** [comment]
We have considered it, it would just be a huge effort to get everything tagged, and it might be very redundant in some sections where a lot of stuff is FOSS, but I will add it to our to do list and at least test it in a few sections to see if I think it works.

**Comment by kushagra-xo** [comment]
let me know if you need any help.

**Comment by beedell-roke** [comment]
@nbats, is that to-do list publicly available? I ask because I don't see a [F]OSS filter.

**Comment by nbats** [comment]
Not on GitHub, but you can view it in our Discord server: 

https://github.com/fmhy/FMHY/wiki/FMHY-Discord
