### ISSUE TITLE
Bring back color scheme

### ISSUE THREAD

**Issue by base-13** [fmhy/FMHYedit#2155]
### Type

Site suggestion

### Add additional context

I feel like that colors of the site have changed after the commit https://github.com/fmhy/FMHYedit/commit/3efa583973e79ae5758369b121f8e5ae086ea87f.
I suggest bringing back those colors as they look more cooler on website, the new ones look slightly darker and dull.
@taskylizard

**Comment by base-13** [comment]
well we can't revert the whole commit but we can still change color values.

**Comment by base-13** [comment]
why?

**Comment by base-13** [comment]
@taskylizard please explain.

**Comment by EkCaAv** [comment]
Bruj
