### ISSUE TITLE
Kids Websites

### ISSUE THREAD

**Issue by EmuAnon34** [fmhy/FMHYedit#2228]
### Type

Site suggestion

### Add additional context

Due to the Cartoon Network website being shut down, I want to provide links for child friendly websites because kids do need their own spaces online.

https://www.funbrain.com
https://www.abcya.com
https://www.starfall.com
https://pbskids.org/

**Comment by nbats** [comment]
Thank you thats very kind but in general we dont really host sites aimed for children.
