### ISSUE TITLE
[ADD] Multiple french piracy websites

### ISSUE THREAD

**Issue by GeekndGamer** [fmhy/FMHYedit#2253]
### Type

Site suggestion

### Add additional context

**Type** : Site suggestion
**Collection** : "Non-English\French / Français"
**Categories** :

**Torrenting / Telecharger** :

Darkiworld : https://darki.world/
Wawacity : https://www.wawacity.ing/

**Streaming** : 

Darkiworld : https://darki.world/
Jallocine : https://jallocine.homes/
Wiflix : https://wiflix-catalogue.pro/
Empire Streaming : https://empire-streaming.app/
Coflix : https://coflix.plus/
Wawacity : https://www.wawacity.ing/
Filmoflix : https://filmoflix.to/

**Comment by nbats** [comment]
Thank you, we'll go through them when we can

**Comment by Vojtak42** [comment]
Could you finally add wawacity? The is no other working page for downloading on FMHY. Also https://www.zone-telechargement.city/ page doesn't work at all.
