### ISSUE TITLE
https://github.com/dmlls/yang should be added

### ISSUE THREAD

**Issue by gog104706** [fmhy/FMHYedit#2261]
### Type

Site suggestion

### Add additional context

https://github.com/dmlls/yang should be added in search tools because it's makes searching too advanced and too fast with custom bangs you can make your own search ways

**Comment by nbats** [comment]
ty but its already linked with DDG in privacy engines, and privacy engines is linked in search engines

**Comment by gog104706** [comment]
> ty but its already linked with DDG in privacy engines, and privacy engines is linked in search engines

Yes, but I did not understand why this addon there
