### ISSUE TITLE
https://images.google.com/ is not for reverse image search it is lens.google.com for reverse image search

### ISSUE THREAD

**Issue by gog104706** [fmhy/FMHYedit#2263]
### Type

Bad sites

### Add additional context

https://images.google.com/ is not for reverse image search it is lens.google.com for reverse image search and i think google lens is very good reverse image search tool maybe it deserves an star and i think bing images should be there

**Comment by nbats** [comment]
sounds good, just got google lens added + starred and bings visual search added
