### ISSUE TITLE
Loginwalled sites it not highlighted in ai section

### ISSUE THREAD

**Issue by gog104706** [fmhy/FMHYedit#2264]
### Type

Bad sites

### Add additional context

There are too many loginwalled sites in aii section For example, Gemini, Claude, sdk.vercel, groq

**Comment by nbats** [comment]
I dont really think people consider forced logins a huge deal with AI, as long as they're free and work well

**Comment by gog104706** [comment]
> I dont really think people consider forced logins a huge deal with AI, as long as they're free and work well

Yes but Claude is not free

**Comment by nbats** [comment]
according to their site they have a free tier 
![image](https://github.com/user-attachments/assets/cfef5763-1663-4fb9-812a-97254c4bb49a)

**Comment by gog104706** [comment]
> according to their site they have a free tier ![image](https://private-user-images.githubusercontent.com/44333466/360162208-cfef5763-1663-4fb9-812a-97254c4bb49a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyODM2MDYsIm5iZiI6MTcyNDI4MzMwNiwicGF0aCI6Ii80NDMzMzQ2Ni8zNjAxNjIyMDgtY2ZlZjU3NjMtMTY2My00ZmI5LTgxMmEtOTcyNTRjNGJiNDlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDIzMzUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhYWU5NmUzODU4YWQyNTE1ZTBmOTBjZDUzNmE1ZDIxMWFmYWM3ZTE0ODIyMTNmMDQyMGFmOTBjYTdjMjkzN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hCHhwaL66UfWAr3Dy4hvU5b0rqNzRNWeRFShWMS1wUg)

Now I tried to register (Phone Number required) they opened the registrations again, normally they were closed since Sonnet 3.5 was released. still it might be good to at least writing the phone requirement

**Comment by nbats** [comment]
sounds good I'll add a note with it
