### ISSUE TITLE
Adding new SPORTS site

### ISSUE THREAD

**Issue by ESO350** [fmhy/FMHYedit#2283]
### Type

Site suggestion

### Add additional context

Hi, 

https://www.google.com/search?client=safari&rls=en&q=methstreams&ie=UTF-8&oe=UTF-8

Methstreams is the new crackstreams. it often changes, but it is always findable and reliable. Please add it into the Sports streaming section. 

Thank you!

**Comment by nbats** [comment]
thank you we'll take a look soon
