### ISSUE TITLE
[ADD] aRcHiV - archive of releases - NFO/SFV/DIZ/JPG/MEDIAINFO/PROOF/FILEiNFO

### ISSUE THREAD

**Issue by scriptzteam** [fmhy/FMHYedit#2287]
### Type

Site suggestion

### Add additional context

Will fit into "Helpful Sites / Apps"

Site shows latest 50 releases - https://archiv.pw/

There is also NFO/SFV/DIZ/JPG/MEDIAINFO/PROOF/FILEiNFO

**Comment by nbats** [comment]
We'll check it out thanks for sharing

**Comment by scriptzteam** [comment]
any news ? :)

**Comment by nbats** [comment]
sorry I bumped it up in queue so it should get added soon
