### ISSUE TITLE
what happened to cock.li?

### ISSUE THREAD

**Issue by fck-12** [fmhy/FMHYedit#2313]
### Type

good site

### Add additional context

used to love seeing it on the list, shame its not there anymore. #unfortunate #dobetter

**Comment by Ends0uls** [comment]
meat riding on cock.li is insane they have a reason to not add stuff if you don't like it make a new one

**Comment by nbats** [comment]
The site has racist shit all over it, there's literally 0% chance its getting re-added as long as its like that.
