### ISSUE TITLE
Picking and choosing which sites to keep based on political opinions, then censoring discussions

### ISSUE THREAD

**Issue by fir3z** [fmhy/FMHYedit#2314]
### Type

Bad sites

### Add additional context

Why is there a double standard of which sites, which have user-generated content on the homepage, get to stay and which ones don't? As I've said in my original PR (https://github.com/fmhy/FMHYedit/pull/2312), which has been closed without response & responses locked, there is a personal vendetta by a maintainer/Discord moderator against the https://cock.li email service. Are the user-generated messages of cock.li magically different compared to the user-generated messages of many other sites' layouts? There is a clear bias in the decisions being made.

@nbats, I look forward to your response with reasoning of why you're deleting issues, closing PR's, and restricting issue creation but this isn't done to other sites that are on FMHY, or the censoring of the 900+ discussion regarding the e-mail service on the Discord suggestions thread-channel. Thanks.

**Comment by nbats** [comment]
The site has racist stuff on the homepage, as long as its there, the site will not be getting added to the wiki. Please stop spamming or I will block you from the github.

**Comment by nbats** [comment]
I mean it should go without saying that racist stuff isn't allowed. No one has ever been confused by that. There's 0% chance its getting added until the racist stuff is removed from the site.

**Comment by nbats** [comment]
Cock.li has the quotes on the sites themselves on purpose, again, 0% chances its getting added until its gone. End of discussion. Go make your own wiki if you want racist sites.

**Comment by nbats** [comment]
Because its not complex and you wont drop it. Again the discussion is over.

**Comment by nbats** [comment]
If you can show me another site that plasters racist stuff as their banner I will remove them, I just haven't seen that.

**Comment by nbats** [comment]
Already explained to you there is literally 0% chance a site with racist banners gets added.

**Comment by x472** [comment]
You draw the line at racism but not drawn child porn because it'd "wipe out an entire section."

Just says it all really.
