### ISSUE TITLE
Remove Dead Project.

### ISSUE THREAD

**Issue by TheOneImprove** [fmhy/FMHYedit#2337]
### Type

Bad sites

### Add additional context

https://fmhy.pages.dev/adblockvpnguide#frontends

https://fmhy.pages.dev/adblockvpnguide#search-engines

[Whoogle](https://github.com/benbusby/whoogle-search/commits/main/) currently does not work and had not get updated since about 5 months.

**Comment by nbats** [comment]
Got it removed ty
