### ISSUE TITLE
Add Hoopla to iOS and Android Reading 

### ISSUE THREAD

**Issue by Thenewchicken55** [fmhy/FMHYedit#2353]
### Type

Site suggestion

### Add additional context

Hoopla is a free Ebook reading app. I recommend it gets added to [android-reading](https://fmhy.net/android-iosguide#android-reading) and more importantly [ios-reading](https://fmhy.net/android-iosguide#ios-reading). 

[hoopla official site](https://www.hoopladigital.com/)
[hoopla iOS](https://apps.apple.com/us/app/hoopla-digital/id580643740)
[hoopla Android](https://play.google.com/store/apps/details/hoopla_Digital?id=com.hoopladigital.android&hl=en_US)

**Comment by nbats** [comment]
we'll take a look thank you
