### ISSUE TITLE
ReXDL contains malware

### ISSUE THREAD

**Issue by 5zx005** [fmhy/FMHYedit#2357]
### Type

Bad sites

### Add additional context

ReXDL (in Android/iOS) has malware, found it in Kingdom Rush Origins apk. 12 vendors detected file as malicious

**Comment by Setsuwaa** [comment]
Are you sure it's not a false positive?

**Comment by nbats** [comment]
Here's the scan, looks like typical false positives to me. 

https://www.virustotal.com/gui/file/b0755b6d5dc60334b7a0f7966f9a9e2f8bc5355e4534d4522a4d11dbc81d100c
