### ISSUE TITLE
Hex values for base64: aHR0cHM6Ly9wYXN0ZWJpbi5jb20vcmF3L1lXWGR4RERM  needs renewal

### ISSUE THREAD

**Issue by androidghosh** [fmhy/FMHYedit#669]
In the base64 option in https://fmhy.pages.dev/base64/ a software (not mentioning its name) with the base64 value: `aHR0cHM6Ly9wYXN0ZWJpbi5jb20vcmF3L1lXWGR4RERM` needs an update in the guide.

In the latest version of the software, in the exe file this portion doesn't exist anymore

![image](https://github.com/fmhy/FMHYedit/assets/17355109/7ef28ebc-6d60-45db-afe3-9d07e1978e9f)

Thus, with this guide we can't patch it anymore. It needs an update.

**Comment by nbats** [comment]
ty I'll get it removed
