### ISSUE TITLE
Add these sites to FMHY

### ISSUE THREAD

**Issue by rarelygoeshere** [fmhy/FMHYedit#680]
Hello, I would like to propose putting the following sites into FHMY:
- https://catmarioo.com/ and https://catmario.eu/ into FHHY's browser games section as they're working japanese and english browser versions of this game respectively.
- https://jklgit.github.io/Image-Comparison-in-Browser/index.html is an Image Comparison Tool on browser that's useful, simple, and user-friendly that I haven't seems to see FMHY has yet
- https://megalodon.jp/ Megalodon, a Japanese online archive site
- https://twoucan.com/ Twoucan by Tinami, a Japanese twitter search site that appears to work similarly to buhitter.

I hope you can consider adding these, thx.

**Comment by KloudAlpha** [comment]
[Create a pull request](https://rentry.co/FMHYedit) to propose changes

**Comment by nbats** [comment]
I'll get em added to our queue ty
