### ISSUE TITLE
Update the wayback machine rentry in the unsafe site list

### ISSUE THREAD

**Issue by Deletecat** [fmhy/FMHYedit#737]
I noticed that wayback machine links were added to the unsafe site list, though there are a couple of missing/broken links on the list:

In Game Sites,
1 Link unavailable - I archived that post a while ago on rentry, see the link here: https://rentry.co/yn8ax - Wayback machine doesn't seem to work well with nsfw links, archive.is works but they don't really like cloudflare dns users 🙃

In software / apps,
3. The link is broken into two parts by a backtick, instead of taking you to the archived rentry page, it takes you to a 404 page depending on what side you click

**Comment by nbats** [comment]
got it updated, thank you
