### ISSUE TITLE
Add fine lock/good lock 

### ISSUE THREAD

**Issue by Turhvjbufv** [fmhy/FMHYedit#782]
Add them to samsung android customization, no trackers and have quite nice customability

**Comment by nbats** [comment]
Alright I found Fine Lock so I'll get that added, but the only link I can find for Good Lock seems to be down.

**Comment by Turhvjbufv** [comment]
Good lock is region locked to the us, galaxy store.  https://apps.samsung.com/appquery/appDetail.as?appId=com.samsung.android.goodlock

**Comment by nbats** [comment]
gotcha thanks for the link, I'll get that added too.
