### ISSUE TITLE
Adding Google Intra

### ISSUE THREAD

**Issue by androidghosh** [fmhy/FMHYedit#786]
[Intra](https://getintra.org/#!/) is a DPI bypassing android app made by Jigsaw, Alphabet. It's just like GoodbyeDPI. You can also use cloudflare and other DNS in there. 
This should be included here, 

![image](https://github.com/fmhy/FMHYedit/assets/17355109/81479f0a-3d26-4dcb-9cb0-13cf3c163d95)

**Comment by nbats** [comment]
Added to the android section, thank you.
