### ISSUE TITLE
[suggestion] Remove Aptoide from android section

### ISSUE THREAD

**Issue by XCE0** [fmhy/FMHYedit#901]
I suggest removing Aptoide from android section as it's very unsafe app store.

Relevant Links:

https://www.zdnet.com/article/details-of-20-million-aptoide-app-store-users-leaked-on-hacking-forum/
https://www.reddit.com/r/androiddev/comments/6pjyn1/malware_we_found_malware_impersonating_our_app_on/

**Comment by nbats** [comment]
Removed, thanks for the heads up
