### ISSUE TITLE
Remove search engine party from adblock privacy -search engines

### ISSUE THREAD

**Issue by XCE0** [fmhy/FMHYedit#907]
searchengine.party has been inactive for a year I think it's time to remove it.

Commits history: https://gitlab.com/nitrohorse/search-engines-compare/-/commits/master

**Comment by XCE0** [comment]
also remove libreengine for the same reason:

https://github.com/liameno/librengine

**Comment by XCE0** [comment]
also replace searx with searx ng link

https://docs.searxng.org/

**Comment by XCE0** [comment]
I think it's also worth removing proprietary  search engines as opensource alternatives are avaliable:

- [Stract](https://trystract.com/)
- [Findx](https://findx.onrender.com/)
-etc...

**Comment by nbats** [comment]
Alright removed searchengine.party, librengine and replaced searx with searx ng. As far as removing proprietary engines goes I'm all for it but I don't have time to click through them all right now
