### ISSUE TITLE
Remove from Android Internet

### ISSUE THREAD

**Issue by XCE0** [fmhy/FMHYedit#909]
I request that the following apps get removed from[ Android internet section](https://fmhy.net/android-iosguide#android-internet):

- [Flynx](https://play.google.com/store/apps/details?id=com.flynx) (no longer Maintained ).
- [Creator Studio](https://play.google.com/store/apps/details?id=com.facebook.creatorstudio) (offical meta app).
- [harpy](https://github.com/robertodoering/harpy) (no longer Maintained ).
- [Shitter](https://github.com/nuclearfog/Shitter) (switched to being mastodon client).

**Comment by nbats** [comment]
removed all 3
