### ISSUE TITLE
Vpns section edit

### ISSUE THREAD

**Issue by XCE0** [fmhy/FMHYedit#913]
https://fmhy.net/adblockvpnguide#vpn

I request removing kaspersky vpn as it logs user ip.

Relevant links:
https://thebestvpn.com/118-vpns-logging-policy/

**Comment by nbats** [comment]
removed

**Comment by nbats** [comment]
I just learned best VPN is a scam, so I'll have to re add some of what we removed, sorry, 

https://www.pcmag.com/news/how-a-vpn-review-site-dominates-google-search-with-a-scam,
