### ISSUE TITLE
remove bromite from android adblock

### ISSUE THREAD

**Issue by XCE0** [fmhy/FMHYedit#916]
https://fmhy.net/android-iosguide#android-adblocking

bromite is no longer in active development .

**Comment by XCE0** [comment]
also remove twidere x from the same section.

**Comment by nbats** [comment]
I removed bromite but it looks like Twidere X was updated 6 months ago

**Comment by XCE0** [comment]
twidere x is no longer working due to new twitter changes.

**Comment by nbats** [comment]
Okay I see, I'll remove that as well
