### ISSUE TITLE
Remove some addons

### ISSUE THREAD

**Issue by XCE0** [fmhy/FMHYedit#917]
https://fmhy.net/adblockvpnguide#privacy-extensions

The following addons are no longer developed:

- [WhatCampaign](https://addons.mozilla.org/en-US/firefox/addon/whatcampaign/)
- [Ping Blocker](https://github.com/dessant/ping-blocker)
- [Lightbeam](https://github.com/princiya/lightbeam-we)
- [CopyGuard](https://github.com/roedesh/copyguard)
- [Nuke-Reddit-History](https://github.com/sr33/ares)
- [Luminous](https://gbaptista.github.io/luminous/doc/en-US/)
- [GNU LibreJS](https://www.gnu.org/software/librejs/)
- [Refer Deez Nuts](https://addons.mozilla.org/en-US/firefox/addon/refer-deez-nuts/)
- [Smart Referer](https://gitlab.com/smart-referrer/smart-referer)
- [Re-Consent](https://cliqz.com/en/magazine/re-consent)
- [chrome-utm-stripper](https://github.com/jparise/chrome-utm-stripper)
- [Cloud Firewall](https://addons.mozilla.org/en-US/firefox/addon/cloud-firewall/)
- [Privacy-Oriented Origin Policy](https://claustromaniac.github.io/poop/)
- [Opt Out Tools](https://add0n.com/opt-out.html)
- [Trackless](https://github.com/ascorbic/trackless)

**Comment by XCE0** [comment]
also:

- [Re-Consent](https://cliqz.com/en/magazine/re-consent)
- [chrome-utm-stripper](https://github.com/jparise/chrome-utm-stripper)
- [Cloud Firewall](https://addons.mozilla.org/en-US/firefox/addon/cloud-firewall/)

**Comment by nbats** [comment]
Alright thank you, I removed everything except: CopyGuard, GNU LibreJS, chrome-utm-stripper as they seem to have been updated somewhat recently.
