### ISSUE TITLE
Moving to open source development platform

### ISSUE THREAD

**Issue by XCE0** [fmhy/FMHYedit#918]
GitHub is not safe for for projects like this and it's posses a several privacy risks, I suggest moving to any open-source alternative like:

- [Gitlab](https://gitlab.com/explore/projects) or any hosted gitlab instance with good rules (from alternativeto I can see [Gitgud](https://gitgud.io) but I not sure about their rules.
- [Sourcehut](https://sr.ht/projects)
- [The Pijul Nest](https://nest.pijul.com/explore)
- Any gitea instance with good rules:
https://git.kescher.at/explore/repos
https://gitea.slowb.ro/explore/repos
https://git.froggi.es/explore/repos

Related link: https://sfconservancy.org/GiveUpGitHub/

**Comment by nullish-cat** [comment]
we have a [gitea](https://git.bignutty.xyz) set up in case we need to switch to that for git hosting. there's also [numerous backups](https://old.reddit.com/r/FREEMEDIAHECKYEAH/wiki/backups) and github isn't the only place to suggest changes (we also have divolt and lemmy)

**Comment by XCE0** [comment]
but I cannot rise issues within the alternative backups, so what I am suggesting is having an issue tracker within Open source alternative so people like me who don't want to use github can use it to rise issues.

If I am wrong about that, and I could post issues on  lemmy kindly correct me.

**Comment by taskylizard** [comment]
Hello, I run the gitea instance nullish mentioned. Currently it *only* mirrors this repository and as such, we don't have any plans to move off github to any other solutions for raising issues. If you want to raise issues with the wiki, we have divolt and lemmy communities (links can be found in this org's readme).
