### ISSUE TITLE
Edit antivirus section

### ISSUE THREAD

**Issue by XCE0** [fmhy/FMHYedit#932]
I think that we need to edit that section, For example :

- Kaspersky beta.
- Avast.(Bad Privacy)
- Remove [ClamAV](https://www.clamav.net/). (bad detection rate)
- Remove [Adaware Antivirus](https://www.adaware.com/free-antivirus-download) (no known protection tests)

**Comment by nbats** [comment]
Alright I removed the two AV's, and we can maybe add Kaspersky beta if you think the free version is useful enough, but we have Avast listed in our unsafe thread so there's no way we can add that.

**Comment by XCE0** [comment]
kaspersky beta is the full kaspersky version, not the free version.

**Comment by nbats** [comment]
Alright we'll check it out
