### ISSUE TITLE
Add "Play Deals" app to "Free Stuff" section

### ISSUE THREAD

**Issue by XCE0** [fmhy/FMHYedit#950]
https://fmhy.net/miscguide#free-stuff

I suggest adding [Play Deals app](https://play.google.com/store/apps/details?id=me.sujanpoudel.playdeals) to free stuff section.

Relevant Links:
[Reddit Post](https://old.reddit.com/r/fossdroid/comments/16sn189/opensourcing_play_deals_paid_apps_deals_a_kmp/)
[App Code](https://github.com/psuzn/Play-Deals) 
[Back-End Code](https://github.com/psuzn/Play-Deals-Backend)

**Comment by nbats** [comment]
I'll get it added, thank you
