### ISSUE TITLE
TeamDrive Indexes base64 doesn't lead anywhere

### ISSUE THREAD

**Issue by IronManMarkRDJ** [fmhy/FMHYedit#957]
https://github.com/fmhy/FMHYedit/blob/main/VideoPiracyGuide.md#-single-server
https://github.com/fmhy/FMHYedit/blob/main/VideoPiracyGuide.md#-drives--directories

In [Live TV / Sports](https://github.com/fmhy/FMHYedit/blob/main/VideoPiracyGuide.md#-live-tv--sports), Awesome IPTV has the "3rd Party Index" emoji but after the 'or' every other link is a storage link so I feel those should have the "Storage Link" emoji.

In [Download Sites](https://github.com/fmhy/FMHYedit/blob/main/VideoPiracyGuide.md#-download-sites), The ↪️ [General DDL Sites](https://www.reddit.com/r/FREEMEDIAHECKYEAH/wiki/download) / [Single Click](https://www.reddit.com/r/FREEMEDIAHECKYEAH/wiki/non-eng#wiki_.25B7_downloading15) at beginning redirects to Downloading in Polish in Non-English but before it redirected to Persian. But I feel the Single Click is not relevant here.

**Comment by nbats** [comment]
Alright thanks for all the updates. I removed the dead TeamDrive lists, switched the 3rd Party Index with our storage icon / link, and removed the "single click" link as most people won't use persian sites regardless of them being single click.
