### ISSUE TITLE
[Suggestion] Add a Legend

### ISSUE THREAD

**Issue by MathewJake365** [fmhy/FMHYedit#959]
Please add a legend which tells what each symbol means.

Like,
🌐 - 
↪️ - 
⭐ - 

and so on...

Also, a note on the order of items in lists would be nice.

E.g. Items in this list are in descending order by...

**Comment by nbats** [comment]
Hey good idea thanks for the suggestion. I'll add a legend at the bottom of the main index page. As far as the order of items goes, quite frankly not every single one of our 30k sites is in any exact order. We do our best to put the best stuff at the top, but its impossible to know enough about every subject for it to be anywhere close to perfect.
